#!/usr/bin/env holen
---
desc: A tiny, pure and fast implementation of Clojure in Clojure for shell scripting.
strategies:
    binary:
        base_url: https://github.com/borkdude/babashka/releases/download/v{{.Version}}/babashka-{{.Version}}-{{.OSArchData.tag}}.tar.gz
        unpack_path: bb
        os_arch:
            linux_amd64:
                tag: linux-amd64
            darwin_amd64:
                tag: macos-amd64
        versions:
          - version: '0.3.1'
            os_arch:
                linux_amd64:
                    sha256sum: 943249a485d42a88c6bc6f7c9cde780039af2dbda8630213451bb9a001562d12
                darwin_amd64:
                    sha256sum: 95675a8baceb79a3736778e0e9f366f573be8f86856899de51ce4a702e4bbb4d
          - version: '0.3.0'
            os_arch:
                linux_amd64:
                    sha256sum: c751cd278d67ce0c7a3b13861787cb081ff6eefa1e529b61fbb2878413b9c103
                darwin_amd64:
                    sha256sum: cfe78b3c93eac0911b6ac5c25ce683ebe6bfd2772ddad7a28a16430363254817
          - base_url: https://github.com/borkdude/babashka/releases/download/v{{.Version}}/babashka-{{.Version}}-{{.OSArchData.tag}}.zip
            os_arch:
                linux_amd64:
                    tag: linux-amd64
                darwin_amd64:
                    tag: macos-amd64
            version: '0.2.13'
            os_arch:
                linux_amd64:
                    sha256sum: 7fb8a5815a343698d0d66dad5da2d6631fbe4cf97b7a21ac52c5d10dbe3a7c2c
                darwin_amd64:
                    sha256sum: 1de34d1d7a2d59904e71d64d525352e73b87bbfd44accc8ca8f8ccbfa5a5ebd2
          - version: '0.2.11'
            os_arch:
                linux_amd64:
                    sha256sum: 38ed193027b2b1ac79efc30fc355eec33d32886e9e2c85d4b418f0541d76a091
                darwin_amd64:
                    sha256sum: 8cd7e54a5c766c3d401268a917071663e0aec092f0a31a06bca4cc18b07bdacd
          - version: '0.2.9'
            os_arch:
                linux_amd64:
                    sha256sum: bb02df1ae1d56739019177aab804418967fb832fe8d78e0324f5a28cf96ab998
                darwin_amd64:
                    sha256sum: 72a3dbac8bc7945f6e2f8584e7e0a844142a2e467e0649a084738252a12ecc56
          - version: '0.2.8'
            os_arch:
                linux_amd64:
                    sha256sum: a960c92c0debe4416b120bbd2ee1debf543343a1585a1a9d36d3916b8eb0db77
                darwin_amd64:
                    sha256sum: d511a781b1e6d7af5b2529b669a8693c4963597b0bcc6fcfbe34e31c32fc146f
          - version: '0.2.7'
            os_arch:
                linux_amd64:
                    sha256sum: 6bbe85a8dbcbdfeb1af924ee576b8c2acc64876a27e469b89bcb0b116830614a
                darwin_amd64:
                    sha256sum: 4c4b789d8728e4363117f3eb6d1d10bc80642ab6473706fd940aefae812cf534
          - version: '0.2.6'
            os_arch:
                linux_amd64:
                    sha256sum: 95225739d08cae0f6f5eeb6fa00143d06cd7db6c0525fdafa41661aae617a1a5
                darwin_amd64:
                    sha256sum: 8b6569fe2937c2e7fd11842a7214bb7442b0dd287bd4ffb95dddb904ddb200fe
          - version: '0.2.5'
            os_arch:
                linux_amd64:
                    sha256sum: e01d65d8099598638028c3935218dd4a1e139183db68faba810b8a9804aa40e4
                darwin_amd64:
                    sha256sum: 67506feaec82c4ae5f4cb46265afcec5da504e91c0035dae3d3f69f65f39f8a2
          - version: '0.2.4'
            os_arch:
                linux_amd64:
                    sha256sum: d56ff45b80226685bf2f804718780a82d30cffa4bda701a28cb170de176bc1fa
                darwin_amd64:
                    sha256sum: 65933e5b598e8b82762f856b8e942ee459db482ad73f704185b2706ccf8b0818
          - version: '0.2.3'
            os_arch:
                linux_amd64:
                    sha256sum: a3aa1ce35cedbbd33361b2523befbd221e26d1fc8fa7db95f15d12ddabe33d94
                darwin_amd64:
                    sha256sum: 70298e0f3bb1f67f5e918134465c135d13fca90e2276c0789f29bed8c740ea5e
          - version: '0.2.2'
            os_arch:
                linux_amd64:
                    sha256sum: 3650a8c7c51732aff2d1d0464e36240d2244709f1466b90142c2bf3b244843a7
                darwin_amd64:
                    sha256sum: b1f1240d50ca7ffa300f25be8428f6d8de5e36014d624eb67f1a6f29ec70bdad
          - version: '0.2.1'
            os_arch:
                linux_amd64:
                    sha256sum: 59ac471d14b4e33a5f871f53a4155cde945dcbc09c6c34f241c034838f5d76ad
                darwin_amd64:
                    sha256sum: 293c977e38acffee1f146b38bc2600103380a844b8113769d6b24d8107789c52
          - version: '0.2.0'
            os_arch:
                linux_amd64:
                    sha256sum: dd42b767c0d46cbe1b3c908a4d3c22c139640ed4149e1f7782ec390eadab9bd0
                darwin_amd64:
                    sha256sum: 00b5b13191f91893f2252569ed2010ceae72bd8098c4347f7149f7d964b12233
          - version: '0.1.2'
            os_arch:
                linux_amd64:
                    sha256sum: 315879c8eb88b4c67a2119dccc0c790e44d40020a94a00498d08a3cfb8db0d0c
                darwin_amd64:
                    sha256sum: e671d710b63826ffeab7efb0b4cfd9e7884f3012ce39e3a52405e21984bfd92a
          - version: '0.1.0'
            os_arch:
                linux_amd64:
                    sha256sum: d9470f10ec0dc3d6374fa6cd1ded6caad68bc47bd72292bbeb955e8f1fe520f2
                darwin_amd64:
                    sha256sum: f9e0f8cbe12dea941ed3eee371d69f831261c16f66e522c379a066d2d26bd37e
          - version: '0.0.98'
            os_arch:
                linux_amd64:
                    sha256sum: fcd6756f7a87f226d2e2a7683b54650577546e78b3535f4d358520042dbbcf93
                darwin_amd64:
                    sha256sum: 719bf45221504c83a5aeba8bd67d37aa9bc872b05a5aa41a6dc2c322ad589539
