#!/usr/bin/env holen
---
desc: A fast CSV toolkit written in Rust.
strategies:
    binary:
        base_url: https://github.com/BurntSushi/xsv/releases/download/{{.Version}}/xsv-{{.Version}}-x86_64-{{.OSArchData.archext}}
        unpack_path: xsv{{.OSArchData.ext}}
        os_arch:
            linux_amd64:
                archext: unknown-linux-musl.tar.gz
            darwin_amd64:
                archext: apple-darwin.tar.gz
            windows_amd64:
                archext: pc-windows-msvc.zip
                ext: .exe
        versions:
          - version: '0.13.0'
            os_arch:
                linux_amd64:
                    sha256sum: d36b1be0f008d6597c2437e764fbe720eb7557f8980e0b03ca709e1020b5c52b
                darwin_amd64:
                    sha256sum: cbc1aa5f078ee3435ecb997e93afe6e3a03c5852393553cd2801000397cc269d
                windows_amd64:
                    sha256sum: 3e319c08456031a9683c19c998ac9f61756a2e456413db17c8e6819b17818a1a
          - version: '0.11.0'
            os_arch:
                linux_amd64:
                    sha256sum: 14808b36bb4fbba7a3ac83b2e60aab59809616b61d4db78e8cfdfa0d909b7f29
                darwin_amd64:
                    sha256sum: b35613b398ea0bfe283606d9cd4b8e7d9ae01f209b54b1c259b167761f338305
                windows_amd64:
                    sha256sum: c6626caa8aee3d05b58bf68a768d8d79e0d198149346aa25dce864342b80360e
